### PR TITLE
fix: if there are spaces in args, then wrap them with quotes

### LINKED ISSUE #157: Incorrect handling for quoted arguments
### Describe the bug

Quoted arguments aren't handled correctly. This is mainly an issue when using `nr` or `nlx` where you might want to a string (with spaces) as a single argument to a command.

e.g. when running the following in the reproduction repo:

```sh
nr print "a b" 'c d' e
```

produces

```js
[ 'a', 'b', 'c', 'd', 'e' ]
```

but running the script via the package manager (`npm`, `pnpm`, `yarn` only):

```sh
npm run print "a b" 'c d' e
```

produces the expected output

```js
[ 'a b', 'c d', 'e' ]
```

**Note:** Looks like `bun run` has the same behaviour as `nr`.

### Reproduction

https://github.com/soorria/ni-quoted-args-bug

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 319.23 MB / 16.00 GB
    Shell: 5.1.16 - /opt/homebrew/bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.110
    Chrome: 113.0.5672.63
    Firefox: 112.0.2
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by FrankFang**
### Description

fix #157

### CODE REVIEW

File: src/parse.ts [hunk 1]
```diff
@@ -25,7 +25,20 @@ export function getCommand(
...
+  const quote = (arg: string) => {
+    const hasIfPresent = arg.startsWith('--if-present ')
+    const prefix = hasIfPresent ? '--if-present ' : ''
+    if (hasIfPresent)
+      arg = arg.slice('--if-present '.length)
+
+    return prefix + (arg.includes(' ')
+      ? arg.indexOf('"')
+        ? `'${arg}'`
+        : `"${arg}"`
```
Comment (antfu) [inline src/parse.ts:37]:
```suggestion
      ? JSON.stringify(arg)
```

We better escape quotes

File: src/parse.ts [hunk 2]
```diff
@@ -25,7 +25,20 @@ export function getCommand(
   if (!c)
     throw new UnsupportedCommand({ agent, command })
 
-  return c.replace('{0}', args.join(' ')).trim()
+  const quote = (arg: string) => {
+    const hasIfPresent = arg.startsWith('--if-present ')
+    const prefix = hasIfPresent ? '--if-present ' : ''
+    if (hasIfPresent)
+      arg = arg.slice('--if-present '.length)
```
Comment (antfu) [inline src/parse.ts:32]: Why is this introduced here?

Comment (FrankFang) [reply src/parse.ts:32]: https://github.com/antfu/ni/blob/d7951e7b5a5822a496c1f8c75c152c379bda4ab7/src/parse.ts#L59
Because `--if-present` has been inserted into the first parameter.
I tried to replace "args[0] = `--if-present ${args[0]}` " to `args.unshift('--if-present')`, but this could lead to other issues, perhaps you could make some overall adjustments
